---
title: "Pluvial Flood Emulation With Hydraulics-Informed Message Passing"
author:
  - Arnold Kazadi
  - "**James Doss-Gollin**"
  - Arlei Silva
date: 2024-06-24
details: "Forty-_P0 On _P1"
year: 2024
bibliography: ../../my-papers.bib
csl: ../../american-geophysical-union.csl
nocite: "@kazadi_icml:2024"

about:
  template: solana
  links:
    - href: https://openreview.net/forum?id=kIHIA6Lr0B
      icon: link
      text: 'Link'

format:
  html:
    page-layout: full
---

Machine Learning (ML) has emerged as a promising alternative to numerical methods for physics-based simulation due to its flexibility and efficiency. Flood modeling is a key case study for ML-based simulation due to its relevance as a tool for supporting preventive and emergency measures to mitigate flood risks. However, the complexity of the topography or domain (ground elevation) and the sparsity of the time-evolving precipitations (external forcing) can be challenging for most existing ML approaches for simulating flooding processes in space and time. Another critical challenge is incorporating physics domain knowledge (hydraulics) into these data-driven models. This paper addresses these challenges by introducing a hydraulics-informed graph neural network for flood simulation. Given a (geographical) region and precipitation data, our model predicts water depths in an auto-regressive fashion. We propose a message-passing framework inspired by the conservation of momentum and mass expressed in the shallow-water equations, which describe the physical process of a flooding event. Empirical results on a dataset covering 9 regions and 7 historical precipitation events demonstrate that our model outperforms the best baseline, and can capture the propagation of water flow more effectively, especially at the very early stage of the flooding event when the amount of water in the domain is scarce. Differently from some of the most recent methods for ML-based simulation, which tend to work well only when the domain is a smooth surface (e.g., flat terrain), we show that our solution achieves accurate results for real ground elevation data.

## BibTeX

```bibtex
@inproceedings{kazadi_icml:2024,
  url = {https://openreview.net/forum?id=kIHIA6Lr0B},
  date = {2024-06-24},
  author = {Kazadi, Arnold and Doss-Gollin, James and Silva, Arlei},
  booktitle = {Forty-{{First International Conference}} on {{Machine Learning}}},
  title = {Pluvial Flood Emulation with Hydraulics-Informed Message Passing},
}
```