---
title: "_P0: _P1 Risks Of Energy Shortfalls Considering Temperature Extremes, Wind And Solar Energy For The _P2 Energy Grid Using A Novel Space-Time Simulation Model"
author:
  - Upmanu Lall
  - Yash Vijay Amonkar
  - David J Farnham
  - Vijay Modi
  - "**James Doss-Gollin**"
date: 2021-12-16
details: "Agu Fall _P0 2021"
year: 2021
bibliography: ../../my-papers.bib
csl: ../../american-geophysical-union.csl
nocite: "@lall_agu:2021"

about:
  template: solana
  links:
    - href: https://agu.confex.com/agu/fm21/meetingapp.cgi/Home/0
      icon: link
      text: 'Link'

format:
  html:
    page-layout: full
---

The February 2021 Texas Freeze highlighted the vulnerability of energy systems and their co-dependent infrastructure systems on climatic factors. As Texas continues to be one of the leaders in the adoption of renewable wind and solar energy, the importance of understanding the joint dependence of the availability of these resources, and of the climate sensitive demand associated with heating and cooling becomes critical. We present a novel space-time simulator based on a generalized k-nearest neighbor method that can generate spatially distributed daily time step simulations of wind power, solar radiation and cooling (CDD) and heating (HDD) degree days. The simulations preserve the cross-field dependence in space and across times in our applications to a 40 year long historical climate re-analysis data from Texas, including the spatial structure of the principal components of the data and their associated temporal spectra. We use the simulations to identify annual maxima of HDD and CDD for different block lengths (e.g., 1, 3, 7, and 14 days) over the entire ERCOT and identify the corresponding available wind and solar resource also over ERCOT. These are then used to identify the joint probability distributions of climate sensitive energy supply and demand, and their associated uncertainty. The estimated multivariate return periods can be used to inform reliable system design. A diagnosis of the atmospheric circulation parameters that lead to the extremes was also conducted for physical insights as to the mechanisms.

## BibTeX

```bibtex
@inproceedings{lall_agu:2021,
  eventtitle = {Fall {{Meeting}} 2021},
  urldate = {2021-12-15},
  url = {https://agu.confex.com/agu/fm21/meetingapp.cgi/Home/0},
  location = {New Orleans, LA},
  publisher = {AGU},
  date = {2021-12-16},
  author = {Lall, Upmanu and Amonkar, Yash Vijay and Farnham, David J and Modi, Vijay and Doss-Gollin, James},
  title = {{{GC42C-08}}: {{The}} Risks of Energy Shortfalls Considering Temperature Extremes, Wind and Solar Energy for the {{Texas}} Energy Grid Using a Novel Space-Time Simulation Model},
}
```