---
title: "H32J-04: Distributed Water and Wastewater Infrastructure System for Climate Change Adaption: A Case Study in the City of Lumberton, NC"
author:
  - Xiangnan Zhou
  - Leonardo Duenas-Osorio
  - Lu Liu
  - Lauren Stadler
  - **James Doss-Gollin**
  - Bezawit Getachew
  - Qilin Li
date: 2021-12-15
details: "AGU Fall Meeting 2021"
year: 2021
nocite: "zhou_agu:2021"

about:
  template: solana
  links:
    - href: https://agu.confex.com/agu/fm21/meetingapp.cgi/Paper/976152
      icon: link
      text: 'Link'

format:
  html:
    page-layout: full
---

Ensuring the reliable distribution of safe drinking water and proper disposal of wastewater is critical to the well-being of modern society. Water treatment plants (WTPs) and wastewater treatment plants (WWTPs) tend to be located near large water bodies for cost-effective pumping of raw water and discharging of sewage downstream. Additionally, most WWTPs are built in low elevation areas to take advantage of gravity flows. Many WTPs and WWTPs are increasingly vulnerable to extreme precipitation events that occur more frequently due to global climate change. Hybrid systems that combine the centralized infrastructure and distributed wastewater treatment units with direct potable reuse (DPR) are an adaptation option for utilities. We investigate the benefit of such hybrid systems in terms of improving resilience to extreme precipitation events with a small city in the U.S., the City of Lumberton, North Carolina. Lumberton was hit by Hurricane Matthew in 2016 and Hurricane Florence in 2018 with different extents of water and wastewater service failure. We build a quantitative model for the water system of Lumberton that enables many-query analysis. We examine the performance of a hybrid system, which has three distributed DPR sites at three existing tank stations that are located either outside 500-year flood hazard zones or in 500-year flood hazard zones with reduced risk, against two hazard scenarios relative to the original system. The first hazard scenario is the flooding of the WTP and the pump station, which reside in the 100-year flood hazard zone. The second is a biological invasion (Escherichia coli) from sewer overflow. We show that the hybrid system has a higher capacity to withstand flooding under certain levels. It can maintain reliable water supply for more than 72 hours if the DPR quantity is maximized, while the original system can only provide less than 24 hours of supply from tanks’ storage. Moreover, the hybrid system contains much-retained impacted areas in case of contaminant invasions as the distributed DPR sites form relatively independent pressure zones. We demonstrate that this modeling framework can provide decision-makers with quantitative data for what-if scenarios with new adaptation alternatives and their synergies (e.g., integrated water and wastewater systems, expanded power backup).

:::{#bibliography}
:::