---
title: "Sequential Adaptation Through Prediction of Structured Climate Risk"
author:
  - **James Doss-Gollin**
date: 2020-01-01
details: ""
year: 2020
nocite: "doss-gollin_dissertation:2020"

about:
  template: solana
  links:
    - text: 'DOI: 10.7916/d8-p9ha-a055 (Open Access)'
      href: https://doi.org/10.7916/d8-p9ha-a055
      icon: link

format:
  html:
    page-layout: full
---

Infrastructure systems around the world face immediate crises and smoldering long-term challenges. Consequently, system owners and managers must balance the need to repair and replace the aging and deteriorating systems already in place against the need for transformative investments in deep decarbonization, climate adaptation, and transportation that will enable long-term competitiveness. Complicating these decisions are deep uncertainties, finite resources, and competing objectives.       These challenges motivate the integration of “hard” investments in physical infrastructure with “soft” instruments like insurance, land use policy, and ecosystem restoration that can improve service, shrink costs, scale up or down as future needs require, and reduce vulnerability to population loss and economic contraction. A critical advantage of soft instruments is that they enable planners to adjust, expand, or reduce them at regular intervals, unlike hard instruments which are difficult to modify once in place. As a result, soft instruments can be precisely tailored to meet near-term needs and conditions, including projections of the quasi-oscillatory, regime-like climate processes that dominate seasonal to decadal hydro-climate variability, thereby reducing the need to guess the needs and hazards of the distant future. The objective of this dissertation is to demonstrate how potentially predictable modes of structured climate variability can inform the design of soft instruments and the formulation of adaptive infrastructure system plans.       Using climate information for sequential adaptation requires developing credible projections of climate variables at relevant time scales. PartI considers the drivers of river floods in large river basins, which is used throughout this dissertation as an example of a high-impact hydroclimate extreme. First, chapter 2 opens by exploring the strengths and limitations of existing methodologies, and by developing a statistical-dynamical causal chain framework within which to consider flood risk on interannual to secular time scales. Next, chapter 3 describes the physical mechanisms responsible for heavy rainfall (90th percentile exceedance)and flooding in the Lower Paraguay River Basin (LPRB), focusing on a November-February(NDJF) 2015-16 flood event that displaced over 170 000 people. This chapter shows that:       1. persistent large-scale conditions over the South American continent during NDJF 2015-16 strengthened the South American Low-Level Jet (SALLJ), bringing warm air and moisture to South East South America (SESA), and steered the jet towards the LPRB, leading to repeated heavy rainfall events and large-scale flooding;       2. while the observed El Niño event contributed to a stronger SALLJ, the Madden-JulienOscillation (MJO) and Atlantic ocean steered the jet over the LPRB; and       3. while numerical sub-seasonal to seasonal (S2S) and seasonal models projected an elevated risk of flooding consistent with the observed El Niño event, they had limited skill at lead times greater than two weeks, suggesting that improved representation of MJO and Atlantic teleconnections could improve regional forecast skill.       Finally, chapter 4 shows how mechanistic understanding of the physical causal chain that leads to a particular hazard of interest – in this case heavy rainfall over a large area in the Ohio River Basin (ORB) – can inform future risks. Taking the GFDL coupled model, version 3 (CM3) as a representative general circulation model (GCM), this chapter shows that       1. the GCM simulates too many regional extreme precipitation (REP) events but under-simulates the occurrence of back to back REP days;       2. REP days show consistent large-scale climate anomalies leading up to the event;       3. indices describing these large-scale anomalies are well simulated by the GCM; and       4. a statistical model describing this causal chain and exploiting simulated large-scale in-dices from the GCM can be used to inform the future occurrence of REP days.       Even the best climate projections must confront epistemic uncertainties. Part II of this dissertation explores how intrinsically flawed projections should inform sequential adaptation.First, chapter5reviews approaches for planning under uncertainty, considering the role of classical decision theory, optimization, probability, and non probabilistic approaches. Next, chapter 6 considers how different physical mechanisms impart predictability at different timescales and the implications of secular, low-frequency cyclical, and high-frequency cyclical variability for selection between instruments with long and short planning periods. In particular, this chapter builds from three assertions regarding the nature of climate risk:       1. different climate risk mitigation instruments have different project lifespans;       2. climate risk varies on many scales; and       3. the processes which dominate this risk over the planning period depend on the planning period itself.       Defining M as the nominal design life of a structural or financial instrument and N as the length of the observational record (a proxy for total informational uncertainty), chapter 7 presents a series of stylized computational experiments to probe the implications of these premises. Key findings are that:       1. quasi-periodic and secular climate signals, with different identifiability and predictability, control future uncertainty and risk;       2. adaptation strategies need to consider how uncertainties in risk projections influence the success of decision pathways; and       3. stylized experiments reveal how bias and variance of climate risk projections influencerisk mitigation over a finite planning period.       Chapter 7 elaborates these findings through a didactic case study of levee heightening in the Netherlands. Integrating a conceptual model of low-frequency variability with credible projections of sea level rise, chapter 7 uses dynamic programming to co-optimize hard (levee increase) and soft (insurance) instruments. Key findings are that       1. large but distant and uncertain changes (e.g., sea level rise) do not necessarily motivate immediate investment in structural risk protection;       2. soft adaptation strategies are robust to different model structures and assumptions while hard instruments perform poorly under conditions for which they were not de-signed; and       3. increasing the hypothetical predictability of near-term climate extremes significantly lowers long-term adaptation costs.       Finally, part III seeks to unpack the conceptual experiments of parts I and II to inform policy and future research. Chapter 8 describes how constructive narratives about climate change can discourage climate fatalism. Instead, chapter 8 emphasizes that while climate change is and will be a critical stressor of infrastructure systems, individuals, communities, and regions have agency and can mitigate its consequences. Finally, chapter9concludes by discussing the key findings of this dissertation and exploring how future work on decision under uncertainty, technology, and earth systems science can aid the design and management of effective infrastructure services.

:::{#bibliography}
:::