---
title: "Water Supply Vulnerability Testing And Robust Planning Analysis With Exploratory Modeling Under Deep Uncertainty"
author:
  - Alyssa A. Graham
date: 2022-01-01
details: ""
year: 2022
bibliography: ../../my-papers.bib
csl: ../../american-geophysical-union.csl
nocite: "@graham_thesis:2022"

about:
  template: solana
  links:
    - href: https://hdl.handle.net/1911/113327
      icon: link
      text: 'Link'

format:
  html:
    page-layout: full
---

Houston faces growing population and severe droughts, suggesting a need for robust water supply planning. Current literature proposes an exploratory modeling approach; however, Texas regions typically project water needs as point predictions based on historical droughts and an uncertainty factor. This thesis employs exploratory modeling to identify under which drought and demand conditions Houston’s water will be insufficient. The model includes a reservoir mass balance, Monte Carlo simulation to generate scenarios, and scenario discovery of shortages regardless of likelihood. Scenarios are compared to projections for context. Generally, scenarios with higher demand and 2011 drought demonstrated moderate supply shortage; scenarios with worse drought demonstrated extreme supply shortage. Houston’s proposed strategies mitigated higher demand, but had negligible mitigation for worse drought conditions. Given that climate change is expected to exacerbate droughts in Texas, this analysis underscores a need for water resource management in Houston to explore many possible futures.

## BibTeX

```bibtex
@thesis{graham_thesis:2022,
  url = {https://hdl.handle.net/1911/113327},
  location = {Houston, TX},
  institution = {Rice University},
  eprinttype = {hdl},
  eprint = {1911/113327},
  date = {2022},
  nameatype = {collaborator},
  namea = {Bedient, Phil and Doss-Gollin, James and Blackburn, Jim and Segner, Ed},
  author = {Graham, Alyssa A.},
  title = {Water Supply Vulnerability Testing and Robust Planning Analysis with Exploratory Modeling under Deep Uncertainty},
}
```