---
title: "Heavy Rainfall In Paraguay During The 2015/16 Austral Summer: Causes And Subseasonal-To-Seasonal Predictive Skill"
author:
  - "**James Doss-Gollin**"
  - Ángel G. Muñoz
  - Simon J. Mason
  - Max Pastén
date: 2018-09
details: "Journal Of Climate"
year: 2018
volume: "31"
issue: "17"
pages: "6669--6685"
bibliography: ../../my-papers.bib
csl: ../../american-geophysical-union.csl
nocite: "@doss-gollin_heavyrainfallinparaguayduringthe2015-2016australsummer:2018"

about:
  template: solana
  links:
    - text: 'DOI: 10.1175/JCLI-D-17-0805.1 (Open Access)'
      href: https://doi.org/10.1175/JCLI-D-17-0805.1
      icon: link
    - icon: github
      text: Code
      href: https://github.com/jdossgollin/2018-paraguay-floods
    - text: Preprint
      icon: file-pdf
      href: https://eartharxiv.org/gzj8n/

format:
  html:
    page-layout: full
---

During the austral summer 2015/16, severe flooding displaced over 170 000 people on the Paraguay River system in Paraguay, Argentina, and southern Brazil. These floods were driven by repeated heavy rainfall events in the lower Paraguay River basin. Alternating sequences of enhanced moisture inflow from the South American low-level jet and local convergence associated with baroclinic systems were conducive to mesoscale convective activity and enhanced precipitation. These circulation patterns were favored by cross-time-scale interactions of a very strong El Niño event, an unusually persistent Madden–Julian oscillation in phases 4 and 5, and the presence of a dipole SST anomaly in the central southern Atlantic Ocean. The simultaneous use of seasonal and subseasonal heavy rainfall predictions could have provided decision-makers with useful information about the start of these flooding events from two to four weeks in advance. Probabilistic seasonal forecasts available at the beginning of November successfully indicated heightened probability of heavy rainfall (90th percentile) over southern Paraguay and Brazil for December–February. Raw subseasonal forecasts of heavy rainfall exhibited limited skill at lead times beyond the first two predicted weeks, but a model output statistics approach involving principal component regression substantially improved the spatial distribution of skill for week 3 relative to other methods tested, including extended logistic regressions. A continuous monitoring of climate drivers impacting rainfall in the region, and the use of statistically corrected heavy precipitation seasonal and subseasonal forecasts, may help improve flood preparedness in this and other regions.

## BibTeX

```bibtex
@article{doss-gollin_heavyrainfallinparaguayduringthe2015-2016australsummer:2018,
  repo = {https://github.com/jdossgollin/2018-paraguay-floods},
  preprint = {https://eartharxiv.org/gzj8n/},
  open = {true},
  urldate = {2026-01-27},
  url = {https://journals.ametsoc.org/doi/10.1175/JCLI-D-17-0805.1},
  doi = {10.1175/JCLI-D-17-0805.1},
  issn = {0894-8755, 1520-0442},
  pages = {6669--6685},
  number = {17},
  volume = {31},
  shortjournal = {J. Clim.},
  journaltitle = {Journal of Climate},
  date = {2018-09},
  author = {Doss-Gollin, James and Muñoz, Ángel G. and Mason, Simon J. and Pastén, Max},
  title = {Heavy Rainfall in {{Paraguay}} during the 2015/16 Austral Summer: Causes and Subseasonal-to-Seasonal Predictive Skill},
}
```